### ISSUE TITLE
Jenkins crash after change in security e.g. to matrix based authorisation

### ISSUE THREAD

**Issue by vorozhko** [GoogleCloudPlatform/continuous-deployment-on-kubernetes#21]
Jenkins crash with:

> Error: Server Error
> 
> The server encountered a temporary error and could not complete your request.
> Please try again in 30 seconds.
> 
> 

then I have to disable security to get it back.
Any idea why it happens and what is workaround?

**Comment by vorozhko** [comment]
The issue looks like related to backend health check. With custom security settings jenkins homepage return 403.

**Comment by TomDeVito** [comment]
@vorozhko is this still an issue for you or did you solve it?

**Comment by ryane** [comment]
@TomDeVito I ran into the same thing and I was able to resolve it by adding a readinessProbe for the /login path (which does not require auth) in my jenkins deployment:

```yml
        readinessProbe:
          httpGet:
            path: /login
            port: 8080
          periodSeconds: 1
          timeoutSeconds: 1
          successThreshold: 1
          failureThreshold: 10
```

https://github.com/kubernetes/contrib/tree/master/ingress/controllers/gce/examples/health_checks
